# Generated by Django 5.0.7 on 2024-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='queue',
            field=models.JSONField(default=list),
        ),
    ]
